# PREPROCESSING `eCO2mix`

## Importation des modules

In [1]:
import sys
import os
import glob
import pandas as pd
# Ajoute le dossier parent au path pour importer data_preprocessing.py
sys.path.append(os.path.abspath(os.path.join('..')))

## Importation des fonction de pr√©-traitement

- `fetch_eCO2mix_data` : t√©l√©charge la source de donn√©e `eCO2mix`
- `convert_all_xls_eCO2mix_data` : converti les fichiers `.xls` en `.csv`
- `concat_eCO2mix_annual_data` : concat√®ne les donn√©es de consommation en un seul Dataframe
- `concat_eCO2mix_tempo_data` : concat√®ne les donn√©e du calendrier TEMPO en un seul Dataframe
- `preprocess_annual_data` : Premier traitement du nettoyage de donn√©e sur les donn√©es de consommation
- `preprocess_tempo_data` : Premier traitement sur le nettoyage de donn√©e sur les donn√©es TEMPO
- `merge_eCO2mix_data`: jointure gauche des donn√©es de consommation et TEMPO sur la date
- `preprocess_eCO2mix_data` : Deuxi√®me traitement de nettoyage sur la donn√©e jointe de consommation et TEMPO
- `preprocess_eCO2mix_data_engineered` : Dernier traitement de nettoyage sur les donn√©es jointe de consommation et TEMPO apr√®s application du feature engineering

**Chaque fonctions de traitement teste la conformit√© de la source de donn√©e.**

In [2]:
from src.data_preprocessing import (
    fetch_eCO2mix_data,
    convert_all_xls_eCO2mix_data,
    concat_eCO2mix_annual_data,
    concat_eCO2mix_tempo_data,
    preprocess_annual_data,
    preprocess_tempo_data,
    merge_eCO2mix_data,
    preprocess_eCO2mix_data,
    preprocess_eCO2mix_data_engineered
    )

## Donn√©e de `eCO2mix`

### T√©l√©chargement des donn√©es

In [3]:
fetch_eCO2mix_data()

üåê Chargement de https://www.rte-france.com/eco2mix/telecharger-les-indicateurs
üîó 24 liens d√©tect√©s (ZIP + Tempo).
‚¨áÔ∏è  T√©l√©chargement ZIP : eCO2mix_RTE_En-cours-TR.zip
‚úÖ Contenu de eCO2mix_RTE_En-cours-TR.zip extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : eCO2mix_RTE_En-cours-Consolide.zip
‚úÖ Contenu de eCO2mix_RTE_En-cours-Consolide.zip extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : eCO2mix_RTE_Annuel-Definitif_2012.zip
‚úÖ Contenu de eCO2mix_RTE_Annuel-Definitif_2012.zip extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : eCO2mix_RTE_Annuel-Definitif_2013.zip
‚úÖ Contenu de eCO2mix_RTE_Annuel-Definitif_2013.zip extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : eCO2mix_RTE_Annuel-Definitif_2014.zip
‚úÖ Contenu de eCO2mix_RTE_Annuel-Definitif_2014.zip extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : eCO2mix_RTE_Annuel-Definitif_2015.zip
‚úÖ Contenu de eCO2mix_RTE_Annuel-Definitif_2015.zip extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : eCO2mix_RTE_Annuel-Definitif_2016.zip
‚úÖ Contenu de eCO2mix_RTE_Annuel-Definitif_2016.zip extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : eCO2mix_RTE_Annuel-Definitif_2017.zip
‚úÖ Contenu de eCO2mix_RTE_Annuel-Definitif_2017.zip extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : eCO2mix_RTE_Annuel-Definitif_2018.zip
‚úÖ Contenu de eCO2mix_RTE_Annuel-Definitif_2018.zip extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : eCO2mix_RTE_Annuel-Definitif_2019.zip
‚úÖ Contenu de eCO2mix_RTE_Annuel-Definitif_2019.zip extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : eCO2mix_RTE_Annuel-Definitif_2020.zip
‚úÖ Contenu de eCO2mix_RTE_Annuel-Definitif_2020.zip extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : eCO2mix_RTE_Annuel-Definitif_2021.zip
‚úÖ Contenu de eCO2mix_RTE_Annuel-Definitif_2021.zip extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : eCO2mix_RTE_Annuel-Definitif_2022.zip
‚úÖ Contenu de eCO2mix_RTE_Annuel-Definitif_2022.zip extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : downloadCalendrierTempo
‚úÖ Contenu de downloadCalendrierTempo extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : downloadCalendrierTempo
‚úÖ Contenu de downloadCalendrierTempo extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : downloadCalendrierTempo
‚úÖ Contenu de downloadCalendrierTempo extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : downloadCalendrierTempo
‚úÖ Contenu de downloadCalendrierTempo extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : downloadCalendrierTempo
‚úÖ Contenu de downloadCalendrierTempo extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : downloadCalendrierTempo
‚úÖ Contenu de downloadCalendrierTempo extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : downloadCalendrierTempo
‚úÖ Contenu de downloadCalendrierTempo extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : downloadCalendrierTempo
‚úÖ Contenu de downloadCalendrierTempo extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : downloadCalendrierTempo
‚úÖ Contenu de downloadCalendrierTempo extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : downloadCalendrierTempo
‚úÖ Contenu de downloadCalendrierTempo extrait dans ../data/external/
‚¨áÔ∏è  T√©l√©chargement ZIP : downloadCalendrierTempo
‚úÖ Contenu de downloadCalendrierTempo extrait dans ../data/external/

### D√©finition des r√©pertoires de donn√©es

In [4]:
xls_folder = os.path.join('..', 'data', 'external')

In [5]:
# Dossiers contenant les fichiers source
wheather_folder = os.path.join("..", "data", "raw")
eco2mix_folder = os.path.join("..","data", "raw")

### Conversion des XLS en CSV

In [6]:
convert_all_xls_eCO2mix_data(xls_folder, eco2mix_folder)

‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2012.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2013.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2014.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2015.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2016.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2017.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2018.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2019.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2020.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2021.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2022.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_En-cours-Consolide.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_En-cours-TR.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_tempo_2014-2015.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_tempo_2015-2016.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_tempo_2016-2017.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_tempo_2017-2018.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_tempo_2018-2019.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_tempo_2019-2020.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_tempo_2020-2021.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_tempo_2021-2022.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_tempo_2022-2023.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_tempo_2023-2024.csv
‚úÖ Fichier converti et nettoy√© : ..\data\raw\eCO2mix_RTE_tempo_2024-2025.csv

### Chargement de toute la consommation horaire

- Concat√©nation des donn√©e de consommation venant de plusieurs sources de donn√©es

In [7]:
df_annual = concat_eCO2mix_annual_data(eco2mix_folder)
df_annual

Lecture des fichiers annuels :
  - ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2012.csv
  - ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2013.csv
  - ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2014.csv
  - ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2015.csv
  - ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2016.csv
  - ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2017.csv
  - ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2018.csv
  - ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2019.csv
  - ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2020.csv
  - ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2021.csv
  - ..\data\raw\eCO2mix_RTE_Annuel-Definitif_2022.csv
  - ..\data\raw\eCO2mix_RTE_En-cours-Consolide.csv
  - ..\data\raw\eCO2mix_RTE_En-cours-TR.csv

,P√©rim√®tre,Nature,Date,Heures,Consommation,Pr√©vision J-1,Pr√©vision J,Fioul,Charbon,Gaz,...,Hydraulique - Fil de l?eau + √©clus√©e,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bio√©nergies - D√©chets,Bio√©nergies - Biomasse,Bio√©nergies - Biogaz,Stockage batterie,D√©stockage batterie,Eolien terrestre,Eolien offshore
0,France,Donn√©es d√©finitives,2012-01-01,00:00,58315,58200,58200,492,25,3816,...,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
1,France,Donn√©es d√©finitives,2012-01-01,00:15,NaN,57700,57550,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,France,Donn√©es d√©finitives,2012-01-01,00:30,58315,57200,56900,492,25,3816,...,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
3,France,Donn√©es d√©finitives,2012-01-01,00:45,NaN,56200,56000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,France,Donn√©es d√©finitives,2012-01-01,01:00,56231,55200,55100,492,25,3834,...,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466939,France,Donn√©es temps r√©el,2025-04-25,22:45,NaN,ND,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
466940,France,Donn√©es temps r√©el,2025-04-25,23:00,NaN,ND,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
466941,France,Donn√©es temps r√©el,2025-04-25,23:15,NaN,ND,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
466942,France,Donn√©es temps r√©el,2025-04-25,23:30,NaN,ND,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
466943,France,Donn√©es temps r√©el,2025-04-25,23:45,NaN,ND,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Premier passage de traitement des consommations horaires

In [8]:
df_annual = preprocess_annual_data(df_annual)
df_annual

             Date Heures Consommation            Datetime
0      2012-01-01  00:00        58315 2012-01-01 00:00:00
2      2012-01-01  00:30        58315 2012-01-01 00:30:00
4      2012-01-01  01:00        56231 2012-01-01 01:00:00
6      2012-01-01  01:30        56075 2012-01-01 01:30:00
8      2012-01-01  02:00        55532 2012-01-01 02:00:00
...           ...    ...          ...                 ...
466698 2025-04-23  10:30        52339 2025-04-23 10:30:00
466699 2025-04-23  10:45        52818 2025-04-23 10:45:00
466700 2025-04-23  11:00        53016 2025-04-23 11:00:00
466701 2025-04-23  11:15        52870 2025-04-23 11:15:00
466702 2025-04-23  11:30        53261 2025-04-23 11:30:00

[272351 rows x 4 columns]

### Chargement de toute la donn√©e TEMPO

- Concat√©nation des donn√©e du calendrier TEMPO venant de plusieurs sources de donn√©es

In [9]:
df_tempo = concat_eCO2mix_tempo_data(eco2mix_folder)
df_tempo

Lecture des fichiers tempo :
  - ..\data\raw\eCO2mix_RTE_tempo_2014-2015.csv
  - ..\data\raw\eCO2mix_RTE_tempo_2015-2016.csv
  - ..\data\raw\eCO2mix_RTE_tempo_2016-2017.csv
  - ..\data\raw\eCO2mix_RTE_tempo_2017-2018.csv
  - ..\data\raw\eCO2mix_RTE_tempo_2018-2019.csv
  - ..\data\raw\eCO2mix_RTE_tempo_2019-2020.csv
  - ..\data\raw\eCO2mix_RTE_tempo_2020-2021.csv
  - ..\data\raw\eCO2mix_RTE_tempo_2021-2022.csv
  - ..\data\raw\eCO2mix_RTE_tempo_2022-2023.csv
  - ..\data\raw\eCO2mix_RTE_tempo_2023-2024.csv
  - ..\data\raw\eCO2mix_RTE_tempo_2024-2025.csv

            Date Type de jour TEMPO
0     2014-09-01               BLEU
1     2014-09-02               BLEU
2     2014-09-03               BLEU
3     2014-09-04               BLEU
4     2014-09-05               BLEU
...          ...                ...
3884  2025-04-20               BLEU
3885  2025-04-21               BLEU
3886  2025-04-22               BLEU
3887  2025-04-23               BLEU
3888  2025-04-24               BLEU

[3889 rows x 2 columns]

### Premier passage de traitement des donn√©es TEMPO

In [10]:
df_tempo = preprocess_tempo_data(df_tempo)
df_tempo

,Date,Type de jour TEMPO_BLANC,Type de jour TEMPO_BLEU,Type de jour TEMPO_ROUGE
0,2014-09-01,False,True,False
1,2014-09-02,False,True,False
2,2014-09-03,False,True,False
3,2014-09-04,False,True,False
4,2014-09-05,False,True,False
...,...,...,...,...
3884,2025-04-20,False,True,False
3885,2025-04-21,False,True,False
3886,2025-04-22,False,True,False
3887,2025-04-23,False,True,False
3888,2025-04-24,False,True,False

### Jointure gauche des donn√©es de consommation horaire et TEMPO

In [11]:
df_merged = merge_eCO2mix_data(df_annual, df_tempo)
df_merged

,Date,Heures,Consommation,Datetime,Type de jour TEMPO_BLANC,Type de jour TEMPO_BLEU,Type de jour TEMPO_ROUGE
0,2012-01-01,00:00,58315,2012-01-01 00:00:00,NaN,NaN,NaN
1,2012-01-01,00:30,58315,2012-01-01 00:30:00,NaN,NaN,NaN
2,2012-01-01,01:00,56231,2012-01-01 01:00:00,NaN,NaN,NaN
3,2012-01-01,01:30,56075,2012-01-01 01:30:00,NaN,NaN,NaN
4,2012-01-01,02:00,55532,2012-01-01 02:00:00,NaN,NaN,NaN
...,...,...,...,...,...,...,...
272346,2025-04-23,10:30,52339,2025-04-23 10:30:00,False,True,False
272347,2025-04-23,10:45,52818,2025-04-23 10:45:00,False,True,False
272348,2025-04-23,11:00,53016,2025-04-23 11:00:00,False,True,False
272349,2025-04-23,11:15,52870,2025-04-23 11:15:00,False,True,False
272350,2025-04-23,11:30,53261,2025-04-23 11:30:00,False,True,False

### Feature Engineering

- `create_date_features` : d√©compose la colonne Date en plusieurs feature distincte caract√©risant des information sur le temps (ann√©e, mois, jour, jour de la semaine...)
- `create_lag_features` : Ajout des variables de d√©calage sur la `Consommation` (*N-1*, *N-2*, *N-3*)
- `create_rolling_features` : Ajout de la moyenne mobile (*moyenne sur les 3 derni√®res consommation*)
- `create_hour_features` : Transformation de l'horaire en features encoder cycliquement par sinus et cosinus

In [12]:
from src.feature_engineering import(
    create_date_features,
    create_lag_features,
    create_rolling_features,
    create_hour_features
)

### Applications du features engineering

In [13]:
df_merged = create_date_features(df_merged)
df_merged = create_lag_features(df_merged, 'Consommation')
df_merged = create_rolling_features(df_merged, 'Consommation')
df_merged = create_hour_features(df_merged)
df_merged

,Date,Heures,Consommation,Datetime,Type de jour TEMPO_BLANC,Type de jour TEMPO_BLEU,Type de jour TEMPO_ROUGE,year,month,day,...,dayofyear,is_weekend,is_end_of_month,Consommation_lag_1,Consommation_lag_2,Consommation_lag_3,Consommation_rolling_mean_3,hour_transformed,hour_sin,hour_cos
0,2012-01-01,00:00,58315,2012-01-01 00:00:00,NaN,NaN,NaN,2012,1,1,...,1,True,False,None,None,None,NaN,0,0.000000,1.000000
1,2012-01-01,00:30,58315,2012-01-01 00:30:00,NaN,NaN,NaN,2012,1,1,...,1,True,False,58315,None,None,NaN,0,0.000000,1.000000
2,2012-01-01,01:00,56231,2012-01-01 01:00:00,NaN,NaN,NaN,2012,1,1,...,1,True,False,58315,58315,None,57620.333333,1,0.258819,0.965926
3,2012-01-01,01:30,56075,2012-01-01 01:30:00,NaN,NaN,NaN,2012,1,1,...,1,True,False,56231,58315,58315,56873.666667,1,0.258819,0.965926
4,2012-01-01,02:00,55532,2012-01-01 02:00:00,NaN,NaN,NaN,2012,1,1,...,1,True,False,56075,56231,58315,55946.000000,2,0.500000,0.866025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272346,2025-04-23,10:30,52339,2025-04-23 10:30:00,False,True,False,2025,4,23,...,113,False,False,52330,53027,52591,52565.333333,10,0.500000,-0.866025
272347,2025-04-23,10:45,52818,2025-04-23 10:45:00,False,True,False,2025,4,23,...,113,False,False,52339,52330,53027,52495.666667,10,0.500000,-0.866025
272348,2025-04-23,11:00,53016,2025-04-23 11:00:00,False,True,False,2025,4,23,...,113,False,False,52818,52339,52330,52724.333333,11,0.258819,-0.965926
272349,2025-04-23,11:15,52870,2025-04-23 11:15:00,False,True,False,2025,4,23,...,113,False,False,53016,52818,52339,52901.333333,11,0.258819,-0.965926
272350,2025-04-23,11:30,53261,2025-04-23 11:30:00,False,True,False,2025,4,23,...,113,False,False,52870,53016,52818,53049.000000,11,0.258819,-0.965926

### Dernier traitement sur le nettoyage et conformit√© de la donn√©e

In [14]:
df_merged = preprocess_eCO2mix_data(df_merged)
df_merged = preprocess_eCO2mix_data_engineered(df_merged)
df_merged

,Date,Heures,Consommation,Type de jour TEMPO_BLANC,Type de jour TEMPO_BLEU,Type de jour TEMPO_ROUGE,year,month,day,weekday,...,dayofyear,is_weekend,is_end_of_month,Consommation_lag_1,Consommation_lag_2,Consommation_lag_3,Consommation_rolling_mean_3,hour_transformed,hour_sin,hour_cos
Datetime,,,,,,,,,,,,,,,,,,,,,
2014-09-01 00:00:00,2014-09-01,00:00,43320,False,True,False,2014,9,1,0,...,244,False,False,43938,44567,42056,43941.666667,0,0.000000,1.000000
2014-09-01 00:30:00,2014-09-01,00:30,41174,False,True,False,2014,9,1,0,...,244,False,False,43320,43938,44567,42810.666667,0,0.000000,1.000000
2014-09-01 01:00:00,2014-09-01,01:00,38430,False,True,False,2014,9,1,0,...,244,False,False,41174,43320,43938,40974.666667,1,0.258819,0.965926
2014-09-01 01:30:00,2014-09-01,01:30,37800,False,True,False,2014,9,1,0,...,244,False,False,38430,41174,43320,39134.666667,1,0.258819,0.965926
2014-09-01 02:00:00,2014-09-01,02:00,37137,False,True,False,2014,9,1,0,...,244,False,False,37800,38430,41174,37789.000000,2,0.500000,0.866025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-23 10:30:00,2025-04-23,10:30,52339,False,True,False,2025,4,23,2,...,113,False,False,52330,53027,52591,52565.333333,10,0.500000,-0.866025
2025-04-23 10:45:00,2025-04-23,10:45,52818,False,True,False,2025,4,23,2,...,113,False,False,52339,52330,53027,52495.666667,10,0.500000,-0.866025
2025-04-23 11:00:00,2025-04-23,11:00,53016,False,True,False,2025,4,23,2,...,113,False,False,52818,52339,52330,52724.333333,11,0.258819,-0.965926
2025-04-23 11:15:00,2025-04-23,11:15,52870,False,True,False,2025,4,23,2,...,113,False,False,53016,52818,52339,52901.333333,11,0.258819,-0.965926
2025-04-23 11:30:00,2025-04-23,11:30,53261,False,True,False,2025,4,23,2,...,113,False,False,52870,53016,52818,53049.000000,11,0.258819,-0.965926

## Exportation de la donn√©e nettoy√©, transform√©

In [15]:
df_merged.to_csv(os.path.join('..', 'data', 'processed', 'eco2mix_data.csv'), index=False)

3. chargement de la donn√©e
    - normalisation selon le `scaler` (√† sauvegarder pour plus tard)
    - split du data (80-20)
4. entrainement et √©valuation
    - entrainement des mod√®les
    - √©valuation
    - sauvegarder le meilleur mod√®le
5. inf√©rence
    - charger la donn√©e necessaire pour la pr√©dictions (date, heure, tempo, temp√©ratures, vacances...)
    - appliquer les features engineering
    - charger le mod√®le
    - √©tablir la pr√©dictions
    - sauvegarder le r√©sulat dans un dataset d'historique de pr√©diction
    - √©valuer